language: cpp
compiler: gcc
install:
  - if [ "$BIGNUM" = "gmp" -o "$FIELD" = "gmp" ]; then sudo apt-get install -qq libgmp-dev; fi
  - if [ "$FIELD" = "64bit_asm" ]; then sudo apt-get install -qq yasm; fi
env:
  global:
    - FIELD=auto      BIGNUM=auto     ENDOMORPHISM=no  BUILD=check  SCALAR=auto
  matrix:
    - SCALAR=64bit
    - SCALAR=32bit
    - FIELD=gmp
    - FIELD=gmp ENDOMORPHISM=yes
    - FIELD=64bit_asm
    - FIELD=64bit_asm ENDOMORPHISM=yes
    - FIELD=64bit
    - FIELD=64bit ENDOMORPHISM=yes
    - FIELD=32bit
    - FIELD=32bit ENDOMORPHISM=yes
    - BIGNUM=gmp
    - BIGNUM=gmp ENDOMORPHISM=yes
    - BIGNUM=openssl
    - BIGNUM=openssl ENDOMORPHISM=yes
    - BUILD=distcheck
before_script: ./autogen.sh
script: ./configure --enable-endomorphism=$ENDOMORPHISM --with-field=$FIELD --with-bignum=$BIGNUM --with-scalar=$SCALAR && make -j2 $BUILD
os: linux
